import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// // app/layout.tsx
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Link from "next/link"; // Import Link for navigation
// import { Landmark, Lock } from "lucide-react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "NOTTO - National Organ & Tissue Transplant Organization",
//   description: "Official Government Portal",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} bg-slate-100 min-h-screen flex flex-col`}>
        
//         {/* --- GLOBAL HEADER (Appears on all pages) --- */}
//         <header className="bg-white border-b border-slate-300 py-3 px-4 md:px-8 flex items-center gap-4 shadow-sm">
//           <div className="flex items-center justify-center w-12 h-12 bg-blue-900 text-white rounded shrink-0">
//             <Landmark size={24} />
//           </div>
//           <div>
//             <h1 className="text-lg font-bold text-blue-900 uppercase tracking-wide leading-tight">
//               National Organ & Tissue Transplant Organization
//             </h1>
//             <p className="text-xs text-slate-500 font-medium uppercase tracking-wider">
//               Ministry of Health & Family Welfare
//             </p>
//           </div>
//           <div className="ml-auto hidden md:block text-right">
//             <p className="text-xs font-bold text-slate-700">Hospital Portal Access</p>
//             <p className="text-xs text-slate-500">Secure Gateway v2.4.0</p>
//           </div>
//         </header>

//         {/* --- GLOBAL NAV BAR (Appears on all pages) --- */}
//         <nav className="bg-blue-900 text-white text-sm py-2 px-8 flex justify-between items-center sticky top-0 z-50">
//           <div className="flex gap-6">
//             {/* The Link component is what connects the pages without refreshing */}
//             <Link href="/" className="hover:underline hover:text-blue-200 transition-colors">
//               Home / Login
//             </Link>
//             <Link href="/guidelines" className="hover:underline hover:text-blue-200 transition-colors">
//               Guidelines
//             </Link>
//             <span className="opacity-50 cursor-not-allowed">Hospital Directory</span>
//             <span className="opacity-50 cursor-not-allowed">Contact Support</span>
//           </div>
//           <div className="flex items-center gap-2 text-blue-200">
//             <Lock size={12} />
//             <span className="text-xs uppercase">256-Bit SSL Encrypted</span>
//           </div>
//         </nav>

//         {/* --- PAGE CONTENT INJECTED HERE --- */}
//         {children}

//         {/* --- GLOBAL FOOTER --- */}
//         <footer className="bg-white border-t border-slate-300 py-4 mt-auto">
//           <div className="max-w-7xl mx-auto px-8 flex flex-col md:flex-row justify-between items-center text-xs text-slate-500">
//             <p>© 2024 National Organ & Tissue Transplant Organization. All Rights Reserved.</p>
//             <div className="flex gap-4 mt-2 md:mt-0">
//               <span className="hover:text-blue-800 cursor-pointer">Privacy Policy</span>
//               <span className="hover:text-blue-800 cursor-pointer">Terms of Use</span>
//             </div>
//           </div>
//         </footer>

//       </body>
//     </html>
//   );
// }
